### ISSUE TITLE
Add `source-checksum` for downloaded resources

### ISSUE THREAD

**Issue by yan-foto** [glasen/snap-ausweisapp2-ce#1]
To add another layer of security, I'd suggest to add `source-checksum`s for downloaded resources. 

Hashes for REINER-SCT can be found [here](http://downloads.reiner-sct.de/LINUX/Hashwerte/Hashwerte.txt) and for the AusweisApp2 are [here](https://github.com/Governikus/AusweisApp2/releases).

I could also send a PR; just wanted to make sure if you'd approve.

**Comment by bentolor** [comment]
@glasen Are you aware of this Issue? There is also a MR waiting for feedback.

**Comment by yan-foto** [comment]
Governikus has already published the latest version (1.20) for Ubuntu under official repositories. You can also use it under Debian (if you have Qt >= 5.12 installed)

I'm closing this issue due to lack of cooperation by the maintainer. This how you **don't** run an open source project.
