### ISSUE TITLE
test debian 10.2  buster

### ISSUE THREAD

**Issue by gerdg-dd** [glasen/snap-ausweisapp2-ce#3]
Hallo,

  $ sudo snap install ausweisapp2-ce
2019-12-17T13:23:14+01:00 INFO snap "ausweisapp2-ce" has bad plugs or slots: network-manager-observe (unknown interface "network-manager-observe")

  $ cd /snap/ausweisapp2-ce/current
  $ ./usr/bin/AusweisApp2 
./usr/bin/AusweisApp2: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.13' not found (required by ./usr/bin/AusweisApp2)

Aktuell ist das so leider nicht in einer Debian stabel installation lauffähig.

libqt5core5a:amd64      5.11.3+dfsg1-1+deb10u1 amd64        Qt 5 core moduleda

MfG
Gerd

**Comment by yan-foto** [comment]
Moin Gerd,

bei Debian Buster wird leider nur Qt 5.11 geliefert. Installiere einfach  Clone mal die offizielle Repo von AusweisApp2 und wechsle auf Tag `1.16.2`. Folge den Anweisungen in Readme und baue einfach selbst diese Version (Du brauchst Toolchain nicht selbstbauen und kannst stattdessen per `apt install` all dependencies vorab installieren).

Es ist nicht die letzte Version, aber gut genug! Governikus hat offizielle Pakete für Ubuntu bereitgestellt, die aber von Qt 5.12 abhängen und können daher auch nicht auf Debian installiert werden. Vergiss also dieses Projekt!

**Comment by gemoxx** [comment]
Hallo,
vielen Danke. Benutze derzeit das Paket aus
https://packages.debian.org/buster-backports/ausweisapp2

**Comment by yan-foto** [comment]
Super! Das wusste ich nicht (schlecht recherchiert!). Danke Dir.
