### ISSUE TITLE
Pairing for Smartphone-as-Cardreader

### ISSUE THREAD

**Issue by rebastion** [glasen/snap-ausweisapp2-ce#7]
Hi

using the App on Ubuntu 18.04 and having trouble getting the SaK/SaC functionality to work. Smartphone and Laptop are on the same Wifi, but the device doesn't show up in the app as smartphone-as-cardreader. What are sources of error I should check to get it working? Thank you!

**Comment by rebastion** [comment]
After today's update of the snap still unable to pair

**Comment by rebastion** [comment]
After today's update of the snap, still nothing. What am I doing wrong? Smartphone and Laptop are in the same Wifi. Settings in the router do allow devices to find each other. Pairing is started. App does not detect any SaC devices

**Comment by rebastion** [comment]
Problem seems to be Firewall. I suggest amending FAQ with a note as to which ports and configs should be in place

**Comment by michas79de** [comment]
So you solved it?! Why didn't you tell how?

**Comment by michas79de** [comment]
Yes, but can you list these ports, which have to be opened?

**Comment by rebastion** [comment]
sorry my friend, it was three years ago and I haven't tried/used it since. The standard Ubuntu firewall tool doesn't give too many config options so you can rather quickly find out I think.
