### ISSUE TITLE
App opens in tray and remains unaccessible

### ISSUE THREAD

**Issue by rebastion** [glasen/snap-ausweisapp2-ce#8]
Today a new update to the snap arrived. However, I can start the app, but it remains in the Ubuntu "tray" and remains basically unaccessible, all I can do is quit the application

**Comment by rebastion** [comment]
Update: Now a double click on the tray icon helps to open it (Ubuntu 18.04), I think the app is slowly getting there in terms of start up behavior

**Comment by rebastion** [comment]
Having the same issue again in the version now supplied by Governikus via PPA (I think, can be found in the Ubuntu Software store). A double click does not open the app from the tray...

**Comment by jhit** [comment]
Have the same issue since I installed a new graphic card from amd and the amdpro driver. previously with Intel graphics, the app worked for me. Maybe some issues with UI rendering in Java?

**Comment by misery** [comment]
Maybe this problem?
https://bugs.launchpad.net/ubuntu/+source/ausweisapp2/+bug/1902897
